/**
 * scripts/init-vault.ts
 * Run after `anchor deploy` to initialize the house vault PDA.
 *
 * Usage:
 *   pnpm ts-node scripts/init-vault.ts
 */

import * as anchor from '@coral-xyz/anchor'
import { Connection, Keypair, PublicKey, clusterApiUrl } from '@solana/web3.js'
import fs from 'fs'
import os from 'os'
import path from 'path'

// ── Config ────────────────────────────────────────────────────
const NETWORK          = 'devnet'
const PROGRAM_ID       = new PublicKey('MagcXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
const HOUSE_EDGE_BPS   = 100  // 1%

async function main() {
  // Load local keypair (the payer / admin)
  const keypairPath = path.join(os.homedir(), '.config', 'solana', 'id.json')
  const rawKeypair  = JSON.parse(fs.readFileSync(keypairPath, 'utf-8'))
  const payer       = Keypair.fromSecretKey(new Uint8Array(rawKeypair))

  console.log(`Admin: ${payer.publicKey.toBase58()}`)

  const connection = new Connection(clusterApiUrl(NETWORK), 'confirmed')
  const balance    = await connection.getBalance(payer.publicKey)
  console.log(`Balance: ${(balance / 1e9).toFixed(3)} SOL`)

  if (balance < 0.1 * 1e9) {
    console.error('⚠️  Low balance! Run: solana airdrop 2')
    process.exit(1)
  }

  // Set up Anchor provider
  const wallet   = new anchor.Wallet(payer)
  const provider = new anchor.AnchorProvider(connection, wallet, { commitment: 'confirmed' })
  anchor.setProvider(provider)

  // Load IDL (generated by anchor build)
  const idlPath = path.join(__dirname, '..', 'target', 'idl', 'casino_engine.json')
  if (!fs.existsSync(idlPath)) {
    console.error('IDL not found. Run: anchor build')
    process.exit(1)
  }
  const idl     = JSON.parse(fs.readFileSync(idlPath, 'utf-8'))
  const program  = new anchor.Program(idl, PROGRAM_ID, provider)

  // Derive vault PDA
  const [vaultPDA, vaultBump] = PublicKey.findProgramAddressSync(
    [Buffer.from('house_vault')],
    PROGRAM_ID
  )
  console.log(`House Vault PDA: ${vaultPDA.toBase58()} (bump: ${vaultBump})`)

  // Check if already initialized
  try {
    const existing = await (program.account as any).houseVault.fetch(vaultPDA)
    console.log(`✅ Vault already initialized. House edge: ${existing.houseEdge} bps`)
    return
  } catch {
    console.log('Vault not initialized yet — creating...')
  }

  // Initialize
  const tx = await (program.methods as any)
    .initializeVault(new anchor.BN(HOUSE_EDGE_BPS))
    .accounts({
      houseVault:    vaultPDA,
      authority:     payer.publicKey,
      systemProgram: anchor.web3.SystemProgram.programId,
    })
    .rpc()

  console.log(`✅ House Vault initialized!`)
  console.log(`   TX: https://explorer.solana.com/tx/${tx}?cluster=devnet`)
  console.log(`   Vault: https://explorer.solana.com/address/${vaultPDA.toBase58()}?cluster=devnet`)
  console.log(`   House edge: ${HOUSE_EDGE_BPS / 100}%`)
}

main().catch(err => {
  console.error('Error:', err)
  process.exit(1)
})
